---
title: "S&DS 220: Homework 7"
subtitle: "Due Friday March 29"
author: "<insert you name>"
output:
  pdf_document: default
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

1. Complete the questions below.  Upload your knitted PDF solutions to Gradescope by the due date.
2. Your solutions should be a combination of writing and R code.  When writing, use complete sentences.
3. Previous homework assignments already had code chunks created for you.  Now it is up to you to insert R code chunks within each problem as needed.
4. You should aim for clear and concise communication (in both words and R code).

## Problem set questions

### Question 1: (Exercise 6.2) Jane Austen novels

Consider the `austen` data set in the `fosdata` package. This data frame contains the complete texts of *Emma* and *Pride and Prejudice*, with additional information which you can read about in the help page for the data set. Each of the following tasks corresponds to using a single `dplyr` verb.

(a) Create a new data frame that consists only of the observations in *Emma*.

*Solution.*

(b) Create a new data frame that contains only the variables `word`, `word_length` and `novel`.

*Solution.*

(c) Create a new data frame that has the words in both books arranged in descending word length.

*Solution.*

(d) Create a new data frame that contains only the longest words that appeared in either of the books.

*Solution.*

(e) What was the mean word length in the two books together?

*Solution.*

(f) Create a new data frame that consists only of the distinct words found in the two books, together with the word length and sentiment score variables. (Hint: use `distinct`).

*Solution.*

\newpage

### Question 2: (Exercise 6.11, 6.15) Baseball batting statistics from the `Lahman` package

This exercise uses the `Batting` data set from the `Lahman` package. This gives the batting statistics of every player who has played baseball from 1871 through the present day.  For these problems, once you identify the `playerID` for the answer, match it with the player's first and last name in the `People` data set, either by filtering for the `playerID` or using a `*join` function.

(a) Which player has the most lifetime at bats without ever having hit a home run?

*Solution.*

(b) Which active player has the most lifetime at bats without ever having hit a home run? (An active player is someone with an entry in the most recent year of the data set).

*Solution.*

(c) Which player has been hit-by-pitch the most number of times?

*Solution.*

\newpage

### Question 3: (Exercise 6.25) Storms

Consider the `storms` data set in the `dplyr` package, from Example 6.5. Recall that `name` and `year` together identify all storms except Zeta (2005-2006).

(a) Which name(s) was/were given to the most storms?

*Solution.*

(b) Which year(s) had the most named storms?

*Solution.*

(c) The second strongest storm named Lili had maximum wind speed of 100. Which name's second strongest storm in terms of maximum wind speed was the strongest among all names' second strongest storms? The `dplyr` function `nth` may be useful for doing this problem.

*Solution.*

\newpage

### Question 4: (Exercise 6.29) Fruits

The data set `fruit` is built into the `stringr` package.

(a) How many fruits have the word "berry" in their name?

*Solution.*

(b) Some of these fruits have the word "fruit" in their name. Find these fruit and remove the word "fruit" to create a list of words that can be made into fruit. (Hint: use `str_remove`)

*Solution.*

\newpage

### Question 5: (Exercise 6.36) Scotland births

Consider the `scotland_births` data set in the `fosdata` package. This data gives the number of births by the age of the mother in Scotland for each year from 1945-2019. This data is in wide format. (Completion of this exercise will be helpful for Exercise 7.28.)

(a) Convert the data into long format with three variable names: `age`, `year` and `births`, where each observation is the number of births in year to mothers that are age years old.

*Solution.*

(b) Convert the `year` to integer by removing the `x` and using `as.integer`.

*Solution.*

(c) Which year had the most babies born to mothers 20-years-old or younger?

*Solution.*
